name: CitiesOfFreedom
authors: [DevKrazy, _Rolyn]
description: Jeu CitiesOfFreedom du network Smedalis.
main: com.devkrazy.citiesoffreedom.CitiesOfFreedom
version: 0.1
api-version: 1.18
commands:
  team:
    description: Commande de gestion des teams.
    usage: /team
    permission: cof.team
  missions:
    description: Commande d'affichage des missions.
    usage: /missions
    permission: cof.missions
  jobs:
    description: Commande d'affichage des métiers.
    usage: /jobs
    permission: cof.jobs
  game:
    description: Commande de gestion de la partie.
    usage: /game
    permission: cof.game